### ISSUE TITLE
Can't record in iframe

### ISSUE THREAD

**Issue by benebsiny** [SideeX/sideex-api#5]
I recorded a page that contained iframe tag, after stopped recording and print all commands, I can't find the command I made in iframe. It seems that sideex didn't record the actions in iframe.

**Comment by Jerryh001** [comment]
It's expected behavior, and will not fix.
FYI: Since the script is inject in main frame, and the iframe and main frame are in different `window` so that we can not know what happened in the frame.

**Comment by benebsiny** [comment]
OK, I got it
